#ifndef FLOWDUMP_GENERATOR_WORKER_HPP
#define FLOWDUMP_GENERATOR_WORKER_HPP

#include "enhanced_flow.hpp"
#include "thread_safe_queue.hpp"
#include <flowgen/generator.hpp>
#include <cstdint>
#include <memory>

namespace flowdump {

/**
 * Generator worker thread
 * Each worker generates flows independently and pushes to shared queue
 */
class GeneratorWorker {
public:
    GeneratorWorker(uint32_t stream_id,
                    const flowgen::GeneratorConfig& config,
                    ThreadSafeQueue<EnhancedFlowRecord>& output_queue,
                    uint64_t flows_to_generate);

    /**
     * Run the worker (call in thread)
     */
    void run();

    /**
     * Get number of flows generated by this worker
     */
    uint64_t flows_generated() const { return flows_generated_; }

private:
    /**
     * Convert basic FlowRecord to EnhancedFlowRecord
     */
    EnhancedFlowRecord enhance_flow(const flowgen::FlowRecord& basic_flow);

    uint32_t stream_id_;
    flowgen::GeneratorConfig config_;
    ThreadSafeQueue<EnhancedFlowRecord>& output_queue_;
    uint64_t flows_to_generate_;
    uint64_t flows_generated_;
};

} // namespace flowdump

#endif // FLOWDUMP_GENERATOR_WORKER_HPP
